apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1aws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1aws
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1aws
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1aws
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1aws
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kmew-tenant/rhtap-demo-app/hacbs-test-project-1aws@sha256:a7c21d97c2a33c700f137c59f88069470e90f064e7482535cc399eaecbbe5fda
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
